##docker file to build the Dev Container (Host) to launch VS Code Remote Containers extension and connect to this container for Ansible development.
FROM my-devcontainer-identity-base:1_0 


LABEL org.opencontainers.image.source="https://github.com/jhoareaumarion/devcontainers"
LABEL org.opencontainers.image.description="Ansible DevContainer"
LABEL org.opencontainers.image.licenses="MPL 2.0"

WORKDIR /workspace

# Copy the installation script
COPY install_ansible.sh /tmp/install_ansible.sh

# Add Yarn GPG key to fix signature verification issues
RUN curl -fsSL https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -

# Run the script
RUN /tmp/install_ansible.sh && \
    rm /tmp/install_ansible.sh


##Configure ansible start (create ansible config file to disable host key checking which is a common issue when connecting to new hosts with ansible)
# Create a directory for your global ansible config if needed
RUN mkdir -p /etc/ansible

# Using '>>' to append just in case it exists
RUN cat <<EOF >> /etc/ansible/ansible.cfg
[defaults]
host_key_checking = False
EOF

# Set the environment variable so Ansible always finds it
ENV ANSIBLE_CONFIG=/etc/ansible/ansible.cfg


COPY post-create.sh /usr/local/bin/post-create.sh
# Validate post create was copied and has execute permissions
RUN ls -l /usr/local/bin/post-create.sh 
RUN chmod +x /usr/local/bin/post-create.sh

CMD ["/bin/bash"]