##base docker file to build the Dev Container (Host) to launch VS Code Remote Containers extension 
## This base image prebakes ssh keys in image for ansibleuser to allow passwordless SSH access to target hosts.
## Dev container can use this base image and distribute the ssh keys to target containers using docker volumes or bind mounts. 
FROM mcr.microsoft.com/devcontainers/python:1-3.12-bullseye
#3.12-bullseye

LABEL org.opencontainers.image.source="https://github.com/jhoareaumarion/devcontainers"
LABEL org.opencontainers.image.description="Ansible DevContainer"
LABEL org.opencontainers.image.licenses="MPL 2.0"

WORKDIR /workspace


# Add Yarn GPG key to fix signature verification issues
RUN curl -fsSL https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -


##Add ssh keys for a user (ansibleuser)  to allow passwordless SSH access to target hosts. 
## This is a common practice to set up SSH keys for the ansible user to allow passwordless SSH access to target hosts.
RUN useradd -m ansibleuser && echo "ansibleuser:ansibleuser" | chpasswd && usermod -aG sudo ansibleuser
    

## Set up the user Identity key pair for Ansible to connect to hosts without password prompts. This is a common practice to set up SSH keys for the ansible user to allow passwordless SSH access to target hosts.    
# 1. Switch to the ansible user so files are created with correct ownership
USER ansibleuser

# 2. Set up the SSH directory and generate the key pair
RUN mkdir -p /home/ansibleuser/.ssh && \
    # -t ed25519: Use the modern, secure EdDSA algorithm
    # -N '': Set an empty passphrase for non-interactive automation
    # -f: Save the key to the standard default location
    ssh-keygen -t ed25519 -N '' -f /home/ansibleuser/.ssh/id_ed25519 && \
    # 3. Apply strict 'Least Privilege' permissions (Industry Best Practice)
    # 700: Only the owner can read/write/enter the directory
    chmod 700 /home/ansibleuser/.ssh && \
    # 600: Only the owner can read/write the private key
    chmod 600 /home/ansibleuser/.ssh/id_ed25519
