FROM mcr.microsoft.com/devcontainers/python:1-3.12-bullseye
#3.12-bullseye

LABEL org.opencontainers.image.source="https://github.com/jhoareaumarion/devcontainers"
LABEL org.opencontainers.image.description="Ansible DevContainer"
LABEL org.opencontainers.image.licenses="MPL 2.0"

WORKDIR /workspace

# Copy the installation script
COPY install_ansible.sh /tmp/install_ansible.sh

# Run the script
RUN /tmp/install_ansible.sh && \
    rm /tmp/install_ansible.sh

COPY post-create.sh /usr/local/bin/post-create.sh
# Validate post create was copied and has execute permissions
RUN ls -l /usr/local/bin/post-create.sh 
RUN chmod +x /usr/local/bin/post-create.sh

CMD ["/bin/bash"]